web: gunicorn fretamento_project.wsgi:application \
     --bind 0.0.0.0:$PORT \
     --workers 4 \
     --worker-class sync \
     --worker-tmp-dir /dev/shm \
     --max-requests 2000 \
     --max-requests-jitter 300 \
     --timeout 120 \
     --keep-alive 10 \
     --access-logfile - \
     --error-logfile - \
     --log-level info \
     --preload