# Generated by Django 4.2.7 on 2025-10-03 17:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GrupoServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_servico", models.TextField()),
                ("horario_base", models.TimeField()),
                ("data_servico", models.DateField()),
                ("pax_total", models.IntegerField(default=0)),
                (
                    "numero_venda",
                    models.TextField(
                        blank=True, help_text="Números de venda concatenados"
                    ),
                ),
                ("eh_prioritario", models.BooleanField(default=False)),
                ("veiculo_recomendado", models.CharField(blank=True, max_length=50)),
                (
                    "preco_estimado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Grupo de Serviços",
                "verbose_name_plural": "Grupos de Serviços",
                "ordering": ["data_servico", "horario_base"],
            },
        ),
        migrations.CreateModel(
            name="ProcessamentoPlanilha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo", models.FileField(upload_to="planilhas/")),
                ("nome_arquivo", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PROCESSANDO", "Processando"),
                            ("CONCLUIDO", "Concluído"),
                            ("ERRO", "Erro"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                ("linhas_processadas", models.IntegerField(default=0)),
                ("linhas_erro", models.IntegerField(default=0)),
                ("log_processamento", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Processamento de Planilha",
                "verbose_name_plural": "Processamentos de Planilhas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_venda", models.CharField(blank=True, max_length=100)),
                ("cliente", models.CharField(max_length=200)),
                ("local_pickup", models.CharField(blank=True, max_length=300)),
                (
                    "pax",
                    models.IntegerField(default=0, help_text="Número de passageiros"),
                ),
                ("horario", models.TimeField(blank=True, null=True)),
                ("data_do_servico", models.DateField()),
                ("servico", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("TRANSFER", "Transfer"),
                            ("DISPOSICAO", "Disposição"),
                            ("TOUR", "Tour"),
                            ("OUTRO", "Outro"),
                        ],
                        default="OUTRO",
                        max_length=20,
                    ),
                ),
                (
                    "direcao",
                    models.CharField(
                        choices=[("IN", "IN"), ("OUT", "OUT"), ("N/A", "N/A")],
                        default="N/A",
                        max_length=10,
                    ),
                ),
                (
                    "aeroporto",
                    models.CharField(
                        choices=[("GIG", "GIG"), ("SDU", "SDU"), ("N/A", "N/A")],
                        default="N/A",
                        max_length=10,
                    ),
                ),
                (
                    "regiao",
                    models.CharField(
                        choices=[
                            ("ZONA SUL", "Zona Sul"),
                            ("SANTOS DUMONT", "Santos Dumont"),
                            ("BARRA", "Barra"),
                            ("CENTRO", "Centro"),
                            ("BUZIOS", "Búzios"),
                            ("ANGRA", "Angra"),
                            ("PETROPOLIS", "Petrópolis"),
                            ("PARATY", "Paraty"),
                            ("MACAE", "Macaé"),
                            ("N/A", "N/A"),
                        ],
                        default="N/A",
                        max_length=20,
                    ),
                ),
                ("eh_regular", models.BooleanField(default=False)),
                ("eh_prioritario", models.BooleanField(default=False)),
                (
                    "linha_original",
                    models.IntegerField(
                        blank=True, help_text="Linha na planilha original", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
                "ordering": ["data_do_servico", "horario"],
            },
        ),
        migrations.CreateModel(
            name="ServicoGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.IntegerField(default=0)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.gruposervico",
                    ),
                ),
                (
                    "servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.servico"
                    ),
                ),
            ],
            options={
                "verbose_name": "Serviço do Grupo",
                "verbose_name_plural": "Serviços dos Grupos",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="CalculoPreco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chave_servico",
                    models.CharField(
                        help_text="Chave do serviço no tarifário", max_length=255
                    ),
                ),
                ("tipo_servico", models.CharField(max_length=100)),
                ("aeroporto", models.CharField(blank=True, max_length=10)),
                ("regiao", models.CharField(blank=True, max_length=100)),
                ("pax", models.IntegerField(default=1)),
                (
                    "tipo_tarifario",
                    models.CharField(
                        choices=[
                            ("JW", "Tarifário JW"),
                            ("MOTORISTAS", "Tarifário Motoristas"),
                            ("PERSONALIZADO", "Preço Personalizado"),
                            ("AUTOMATICO", "Cálculo Automático"),
                        ],
                        default="AUTOMATICO",
                        max_length=20,
                    ),
                ),
                (
                    "veiculo_recomendado",
                    models.CharField(
                        choices=[
                            ("Executivo", "Executivo"),
                            ("Van 15 lugares", "Van 15 lugares"),
                            ("Van 18 lugares", "Van 18 lugares"),
                            ("Micro", "Micro"),
                            ("Ônibus", "Ônibus"),
                        ],
                        max_length=20,
                    ),
                ),
                ("preco_base", models.DecimalField(decimal_places=2, max_digits=10)),
                ("preco_final", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "custo_operacional",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("margem", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rentabilidade", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "data_calculo",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "detalhes_json",
                    models.JSONField(
                        blank=True,
                        help_text="Detalhes adicionais do cálculo",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cálculo de Preço",
                "verbose_name_plural": "Cálculos de Preços",
                "ordering": ["-data_calculo"],
                "indexes": [
                    models.Index(
                        fields=["chave_servico"], name="core_calcul_chave_s_9dc780_idx"
                    ),
                    models.Index(
                        fields=["tipo_servico"], name="core_calcul_tipo_se_c3091f_idx"
                    ),
                    models.Index(
                        fields=["data_calculo"], name="core_calcul_data_ca_0a1106_idx"
                    ),
                ],
            },
        ),
    ]
