# Generated by Django 4.2.7 on 2025-10-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processamentoplanilha",
            name="data_primeira_linha",
            field=models.DateField(
                blank=True, help_text="Data do primeiro serviço na planilha", null=True
            ),
        ),
        migrations.AddField(
            model_name="processamentoplanilha",
            name="data_ultima_linha",
            field=models.DateField(
                blank=True, help_text="Data do último serviço na planilha", null=True
            ),
        ),
        migrations.AddField(
            model_name="processamentoplanilha",
            name="tamanho_arquivo",
            field=models.BigIntegerField(
                default=0, help_text="Tamanho do arquivo em bytes"
            ),
        ),
        migrations.AddField(
            model_name="processamentoplanilha",
            name="total_servicos_criados",
            field=models.IntegerField(
                default=0, help_text="Total de serviços criados a partir desta planilha"
            ),
        ),
        migrations.AddField(
            model_name="processamentoplanilha",
            name="usuario_upload",
            field=models.CharField(
                blank=True, help_text="Usuário que fez o upload", max_length=150
            ),
        ),
    ]
