# Generated by Django 4.2.7 on 2025-10-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_processamentoplanilha_data_primeira_linha_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servico",
            name="processamento",
            field=models.ForeignKey(
                blank=True,
                help_text="Processamento que gerou este serviço",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="servicos_criados",
                to="core.processamentoplanilha",
            ),
        ),
    ]
