# Generated by Django 4.2.7 on 2025-10-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_servico_processamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servico",
            name="processamento",
        ),
        migrations.AddField(
            model_name="servico",
            name="arquivo_origem",
            field=models.CharField(
                blank=True, help_text="Nome do arquivo de origem", max_length=255
            ),
        ),
    ]
