# Generated by Django 4.2.7 on 2025-10-14 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_remove_servico_processamento_servico_arquivo_origem"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Criação"),
                            ("UPDATE", "Atualização"),
                            ("DELETE", "Exclusão"),
                            ("UPLOAD", "Upload"),
                            ("DOWNLOAD", "Download"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("VIEW", "Visualização"),
                            ("EXPORT", "Exportação"),
                            ("IMPORT", "Importação"),
                            ("GENERATE", "Geração"),
                            ("PROCESS", "Processamento"),
                            ("ERROR", "Erro"),
                            ("SUCCESS", "Sucesso"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("details", models.TextField(blank=True)),
                ("object_type", models.CharField(blank=True, max_length=50)),
                ("object_id", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Atividade",
                "verbose_name_plural": "Logs de Atividades",
                "db_table": "core_activity_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
