# Generated by Django 4.2.7 on 2025-10-14 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_activitylog"),
    ]

    operations = []
