# Generated by Django 5.2 on 2025-10-20 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20251014_1555"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["-created_at"], name="idx_act_created"),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_act_user_created"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["activity_type"], name="idx_act_type"),
        ),
        migrations.AddIndex(
            model_name="processamentoplanilha",
            index=models.Index(fields=["-created_at"], name="idx_proc_created"),
        ),
        migrations.AddIndex(
            model_name="processamentoplanilha",
            index=models.Index(fields=["status"], name="idx_proc_status"),
        ),
        migrations.AddIndex(
            model_name="servico",
            index=models.Index(fields=["data_do_servico"], name="idx_servico_data"),
        ),
        migrations.AddIndex(
            model_name="servico",
            index=models.Index(fields=["tipo"], name="idx_servico_tipo"),
        ),
        migrations.AddIndex(
            model_name="servico",
            index=models.Index(fields=["aeroporto"], name="idx_servico_aeroporto"),
        ),
        migrations.AddIndex(
            model_name="servico",
            index=models.Index(fields=["eh_prioritario"], name="idx_servico_prior"),
        ),
        migrations.AddIndex(
            model_name="servico",
            index=models.Index(
                fields=["-data_do_servico"], name="idx_servico_data_desc"
            ),
        ),
        migrations.AddIndex(
            model_name="servico",
            index=models.Index(
                fields=["data_do_servico", "horario"], name="idx_servico_data_hora"
            ),
        ),
    ]
