# Generated by Django 4.2.7 on 2025-10-03 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Escala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(unique=True)),
                ("otimizada", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "van1_grupos",
                    models.ManyToManyField(
                        blank=True, related_name="escalas_van1", to="core.gruposervico"
                    ),
                ),
                (
                    "van2_grupos",
                    models.ManyToManyField(
                        blank=True, related_name="escalas_van2", to="core.gruposervico"
                    ),
                ),
            ],
            options={
                "verbose_name": "Escala",
                "verbose_name_plural": "Escalas",
                "ordering": ["data"],
            },
        ),
        migrations.CreateModel(
            name="AlocacaoVan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "van",
                    models.CharField(
                        choices=[("VAN1", "Van 1"), ("VAN2", "Van 2")], max_length=10
                    ),
                ),
                (
                    "ordem",
                    models.IntegerField(default=0, help_text="Ordem dentro da van"),
                ),
                (
                    "escala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alocacoes",
                        to="escalas.escala",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.gruposervico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alocação Van",
                "verbose_name_plural": "Alocações Van",
                "ordering": ["van", "ordem"],
                "unique_together": {("escala", "grupo")},
            },
        ),
    ]
