# Generated by Django 4.2.7 on 2025-10-03 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("escalas", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="alocacaovan",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="escala",
            name="otimizada",
        ),
        migrations.RemoveField(
            model_name="escala",
            name="van1_grupos",
        ),
        migrations.RemoveField(
            model_name="escala",
            name="van2_grupos",
        ),
        migrations.AddField(
            model_name="alocacaovan",
            name="automatica",
            field=models.BooleanField(
                default=True, help_text="Se foi alocada automaticamente"
            ),
        ),
        migrations.AddField(
            model_name="alocacaovan",
            name="lucratividade",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Score de lucratividade",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="alocacaovan",
            name="preco_calculado",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="alocacaovan",
            name="servico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.servico",
            ),
        ),
        migrations.AddField(
            model_name="alocacaovan",
            name="veiculo_recomendado",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="escala",
            name="data_origem",
            field=models.DateField(
                blank=True, help_text="Data de onde os dados foram puxados", null=True
            ),
        ),
        migrations.AddField(
            model_name="escala",
            name="etapa",
            field=models.CharField(
                choices=[
                    ("ESTRUTURA", "Estrutura Criada"),
                    ("DADOS_PUXADOS", "Dados Puxados"),
                    ("OTIMIZADA", "Otimizada"),
                ],
                default="ESTRUTURA",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="alocacaovan",
            unique_together={("escala", "servico")},
        ),
        migrations.RemoveField(
            model_name="alocacaovan",
            name="grupo",
        ),
    ]
