# Generated by Django 4.2.7 on 2025-10-03 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("escalas", "0002_alter_alocacaovan_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrupoServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "van",
                    models.CharField(
                        choices=[("VAN1", "Van 1"), ("VAN2", "Van 2")], max_length=10
                    ),
                ),
                (
                    "ordem",
                    models.IntegerField(
                        default=0, help_text="Ordem do grupo dentro da van"
                    ),
                ),
                ("cliente_principal", models.CharField(max_length=200)),
                ("servico_principal", models.TextField()),
                (
                    "local_pickup_principal",
                    models.CharField(blank=True, max_length=200),
                ),
                ("total_pax", models.IntegerField(default=0)),
                (
                    "total_valor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "escala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grupos",
                        to="escalas.escala",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de Serviços",
                "verbose_name_plural": "Grupos de Serviços",
                "ordering": ["van", "ordem"],
            },
        ),
        migrations.CreateModel(
            name="ServicoGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alocacao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grupo_info",
                        to="escalas.alocacaovan",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicos",
                        to="escalas.gruposervico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Serviço no Grupo",
                "verbose_name_plural": "Serviços nos Grupos",
            },
        ),
    ]
