# Generated by Django 4.2.7 on 2025-10-03 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("escalas", "0003_gruposervico_servicogrupo"),
    ]

    operations = [
        migrations.AddField(
            model_name="escala",
            name="aprovada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="escalas_aprovadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="escala",
            name="data_aprovacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="escala",
            name="observacoes_aprovacao",
            field=models.TextField(
                blank=True, help_text="Observações sobre a aprovação/rejeição"
            ),
        ),
        migrations.AddField(
            model_name="escala",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("APROVADA", "Aprovada"),
                    ("REJEITADA", "Rejeitada"),
                ],
                default="PENDENTE",
                max_length=20,
            ),
        ),
    ]
