# Generated by Django 4.2.7 on 2025-10-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escalas", "0004_escala_aprovada_por_escala_data_aprovacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alocacaovan",
            name="detalhes_precificacao",
            field=models.JSONField(
                blank=True,
                help_text="Detalhes de como o preço foi calculado",
                null=True,
            ),
        ),
    ]
