# Generated by Django 4.2.7 on 2025-10-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escalas", "0005_alocacaovan_detalhes_precificacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="alocacaovan",
            name="status_alocacao",
            field=models.CharField(
                choices=[("ALOCADO", "Alocado"), ("NAO_ALOCADO", "Não alocado")],
                default="ALOCADO",
                help_text="Status da alocação após otimização",
                max_length=20,
            ),
        ),
    ]
