# Generated by Django 4.2.7 on 2025-10-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escalas", "0006_alocacaovan_status_alocacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="gruposervico",
            name="numeros_venda",
            field=models.TextField(
                blank=True,
                help_text="Números de venda concatenados separados por ' / '",
            ),
        ),
    ]
