# Generated by Django 4.2.7 on 2025-10-06 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("escalas", "0007_gruposervico_numeros_venda"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEscala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("CRIAR", "Escala Criada"),
                            ("PUXAR_DADOS", "Dados Puxados"),
                            ("OTIMIZAR", "Escala Otimizada"),
                            ("FORMATAR", "Escala Formatada"),
                            ("APROVAR", "Escala Aprovada"),
                            ("REJEITAR", "Escala Rejeitada"),
                            ("EXPORTAR", "Escala Exportada"),
                            ("EXCLUIR", "Escala Excluída"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "descricao",
                    models.TextField(
                        blank=True, help_text="Detalhes da ação realizada"
                    ),
                ),
                (
                    "dados_antes",
                    models.JSONField(
                        blank=True, help_text="Estado antes da ação", null=True
                    ),
                ),
                (
                    "dados_depois",
                    models.JSONField(
                        blank=True, help_text="Estado depois da ação", null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "escala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="escalas.escala",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Escala",
                "verbose_name_plural": "Logs de Escalas",
                "ordering": ["-timestamp"],
            },
        ),
    ]
