# Generated by Django 4.2.7 on 2025-10-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escalas", "0008_logescala"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="alocacaovan",
            index=models.Index(
                fields=["escala"], name="escalas_alo_escala__bc289a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alocacaovan",
            index=models.Index(fields=["van"], name="escalas_alo_van_e60f33_idx"),
        ),
        migrations.AddIndex(
            model_name="alocacaovan",
            index=models.Index(fields=["ordem"], name="escalas_alo_ordem_5b0d75_idx"),
        ),
        migrations.AddIndex(
            model_name="alocacaovan",
            index=models.Index(
                fields=["status_alocacao"], name="escalas_alo_status__6dc5f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alocacaovan",
            index=models.Index(
                fields=["escala", "van"], name="escalas_alo_escala__bb4f81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alocacaovan",
            index=models.Index(
                fields=["van", "ordem"], name="escalas_alo_van_31ceeb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alocacaovan",
            index=models.Index(
                fields=["escala", "status_alocacao"],
                name="escalas_alo_escala__e437dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="escala",
            index=models.Index(fields=["data"], name="escalas_esc_data_826af7_idx"),
        ),
        migrations.AddIndex(
            model_name="escala",
            index=models.Index(fields=["etapa"], name="escalas_esc_etapa_a36e29_idx"),
        ),
        migrations.AddIndex(
            model_name="escala",
            index=models.Index(fields=["status"], name="escalas_esc_status_958b92_idx"),
        ),
        migrations.AddIndex(
            model_name="escala",
            index=models.Index(
                fields=["data", "etapa"], name="escalas_esc_data_b33b7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="escala",
            index=models.Index(
                fields=["created_at"], name="escalas_esc_created_84c397_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gruposervico",
            index=models.Index(
                fields=["escala"], name="escalas_gru_escala__95a2d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gruposervico",
            index=models.Index(fields=["van"], name="escalas_gru_van_264dd5_idx"),
        ),
        migrations.AddIndex(
            model_name="gruposervico",
            index=models.Index(fields=["ordem"], name="escalas_gru_ordem_35ebbb_idx"),
        ),
        migrations.AddIndex(
            model_name="gruposervico",
            index=models.Index(
                fields=["escala", "van"], name="escalas_gru_escala__43d16c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gruposervico",
            index=models.Index(
                fields=["van", "ordem"], name="escalas_gru_van_7904c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gruposervico",
            index=models.Index(
                fields=["created_at"], name="escalas_gru_created_aa4981_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gruposervico",
            index=models.Index(
                fields=["updated_at"], name="escalas_gru_updated_8306c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logescala",
            index=models.Index(
                fields=["escala"], name="escalas_log_escala__28da84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logescala",
            index=models.Index(fields=["acao"], name="escalas_log_acao_b298bc_idx"),
        ),
        migrations.AddIndex(
            model_name="logescala",
            index=models.Index(
                fields=["usuario"], name="escalas_log_usuario_c728e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logescala",
            index=models.Index(
                fields=["timestamp"], name="escalas_log_timesta_3b729f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logescala",
            index=models.Index(
                fields=["escala", "acao"], name="escalas_log_escala__ace43f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logescala",
            index=models.Index(
                fields=["escala", "timestamp"], name="escalas_log_escala__90bd19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logescala",
            index=models.Index(
                fields=["usuario", "timestamp"], name="escalas_log_usuario_79ccf8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicogrupo",
            index=models.Index(fields=["grupo"], name="escalas_ser_grupo_i_12c0f5_idx"),
        ),
        migrations.AddIndex(
            model_name="servicogrupo",
            index=models.Index(
                fields=["alocacao"], name="escalas_ser_alocaca_c45e10_idx"
            ),
        ),
    ]
