# Generated by Django 4.2.7 on 2025-10-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escalas", "0009_alocacaovan_escalas_alo_escala__bc289a_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logescala",
            name="acao",
            field=models.CharField(
                choices=[
                    ("CRIAR", "Escala Criada"),
                    ("PUXAR_DADOS", "Dados Puxados"),
                    ("OTIMIZAR", "Escala Otimizada"),
                    ("FORMATAR", "Escala Formatada"),
                    ("APROVAR", "Escala Aprovada"),
                    ("REJEITAR", "Escala Rejeitada"),
                    ("EXPORTAR", "Escala Exportada"),
                    ("EXCLUIR", "Escala Excluída"),
                    ("ADICIONAR_MANUAL", "Serviço Adicionado Manualmente"),
                ],
                max_length=20,
            ),
        ),
    ]
