# Generated by Django 4.2.7 on 2025-10-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escalas", "0010_alter_logescala_acao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alocacaovan",
            name="status_alocacao",
            field=models.CharField(
                choices=[("ALOCADO", "Alocado"), ("NAO_ALOCADO", "Não alocado")],
                default="NAO_ALOCADO",
                help_text="Status da alocação após otimização",
                max_length=20,
            ),
        ),
    ]
