# Generated by Django 4.2.7 on 2025-10-14 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Foto de perfil do usuário",
                        null=True,
                        upload_to="profiles/avatars/",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Telefone de contato",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Departamento ou setor",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Breve descrição sobre o usuário",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, help_text="Data de nascimento", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "theme_preference",
                    models.CharField(
                        choices=[("light", "Claro"), ("dark", "Escuro")],
                        default="light",
                        help_text="Tema preferido da interface",
                        max_length=10,
                    ),
                ),
                (
                    "language_preference",
                    models.CharField(
                        choices=[("pt-br", "Português (Brasil)"), ("en", "English")],
                        default="pt-br",
                        help_text="Idioma preferido",
                        max_length=10,
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, help_text="Receber notificações por email"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil do Usuário",
                "verbose_name_plural": "Perfis dos Usuários",
                "ordering": ["-created_at"],
            },
        ),
    ]
