# Generated by Django 4.2.7 on 2025-10-14 16:23

from django.db import migrations


def create_user_profiles(apps, schema_editor):
    """Criar perfis para usuários existentes que não têm perfil"""
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('authentication', 'UserProfile')
    
    for user in User.objects.all():
        if not hasattr(user, 'profile'):
            UserProfile.objects.create(user=user)


def reverse_create_user_profiles(apps, schema_editor):
    """Reverter a criação de perfis"""
    # Não fazer nada na reversão para preservar dados
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_user_profiles, reverse_create_user_profiles),
    ]
