# Generated by Django 4.2.7 on 2025-10-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_auto_20251014_1323"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="bio",
        ),
    ]
