# Generated by Django 4.2.7 on 2025-10-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_remove_userprofile_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="phone",
        ),
    ]
