site_name: Fretamento Intertouring - Documentação
site_description: Sistema de Gestão de Escalas e Fretamento
site_author: Equipe Fretamento Intertouring
site_url: https://andersonodev.github.io/fretamento

repo_name: fretamento
repo_url: https://github.com/andersonodev/fretamento

theme:
  name: material
  language: pt
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Modo escuro
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      lang: pt

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols

nav:
  - Home: index.md
  - 🎯 Visão Geral:
    - Arquitetura Completa: architecture.md
    - Algoritmos e Lógica: algorithms.md
    - Business Intelligence: business-intelligence.md
  - 👤 Guia do Usuário:
    - Introdução: user-guide/introducao.md
    - Gestão de Escalas: user-guide/escalas.md
  - 🔧 Manual Técnico:
    - Visão Geral: technical/arquitetura.md
  - 🚀 Deploy e Infraestrutura:
    - Deploy com Docker: deploy/docker.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/andersonodev/fretamento-intertouring
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/andersonodev
      name: LinkedIn
  generator: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

copyright: Copyright &copy; 2024 Fretamento Intertouring - Desenvolvido com ❤️ para otimizar operações de fretamento