# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - fretamento

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-azure.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-azure.txt
      
      - name: Run Django checks
        run: |
          python manage.py check --deploy
        env:
          DEBUG: False
          USE_DOCKER: False
          SECRET_KEY: 'django-insecure-build-key-temp-12345'
          DJANGO_SETTINGS_MODULE: 'fretamento_project.settings'
      
      - name: Collect static files (Django)
        run: |
          python manage.py collectstatic --noinput --clear
        env:
          DEBUG: False
          USE_DOCKER: False
          SECRET_KEY: 'django-insecure-build-key-temp-12345'
          DJANGO_SETTINGS_MODULE: 'fretamento_project.settings'

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/
            !.git/
            !.github/
            !docs/
            !tests/
            !__pycache__/
            !*.pyc
            !.env
            !.env.*
            !logs/
            !media/planilhas/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'fretamento'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8C31DA2AEC6C43838B2B3095C9D76B68 }}